language: python
python:
  - "3.5"
dist: precise
install: pip install tox
script:
  - tox
  - shellcheck -s dash ubuntu-advantage update-motd.d/*
addons:
  apt:
    sources:
      - debian-sid
    packages:
      - shellcheck
