language: python
dist: focal

install:
  # Required so `git describe` will definitely find a tag; see
  # https://github.com/travis-ci/travis-ci/issues/7422
  - git fetch --unshallow
  - make testdeps
script:
  - make test

matrix:
  fast_finish: true
  include:
    - python: 3.8
      env: TOXENV=behave TEST_BUILD_ENV=1
      script:
          # bionic has lxd from deb installed, remove it first to avoid
          # confusion over versions
          - echo $TRAVIS_BRANCH
          - echo $TRAVIS_BUILD_DIR
          - echo "$TRAVIS_BRANCH" >> /tmp/build.sh
          - echo "HOST_WORKDIR=$(pwd)" >> /tmp/build.sh
          - echo "TEST_BUILD_TRAVIS=1" >> /tmp/build.sh
          - source /tmp/build.sh
          - echo $TEST_BUILD_TRAVIS
          - export TEST_BUILD_PUSH=1
#          - make deps
 #         - dpkg-buildpackage -us -uc
          # - dpkg -i /var/tmp/ubuntu-advantage-tools_20.4_amd64.deb #hardcoding, need to check just .deb file
  #        - cp ubuntu-advantage-tools_20.4_amd64.deb /tmp
   #       - sudo apt-get remove --yes --purge lxd lxd-client
    #      - sudo rm -Rf /var/lib/lxd
          - sudo snap install lxd
          - sudo lxd init --auto
          - sudo usermod -a -G lxd $USER
          - sg lxd -c 'UACLIENT_BEHAVE_BUILD_DAILY=1 make test'
